project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - butterfly-wings.qmd
    - collaboration-networks.qmd
    - curriculum-vitae.qmd
  resources:
    - files/Glory-Kellogg-CV.pdf

website:
  title: "Glory Kellogg"
  favicon: images/favicon.png
  search: false
  navbar: false

  page-footer:
    left: "© 2026 Glory Kellogg"
    right: "Built with Quarto"

format:
  html:
    theme: simplex
    css: styles.css
    include-before-body: header.html
    toc: false